apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    # Filebeat configuration file
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /home/mobaxterm/MyDocuments/datapandas/logs_files/*.log
      exclude_files: ['\.gz$']
    setup.ilm.enabled: false
    setup.template.overwrite: true
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
      index: "filebeat-%{+yyyy.MM.dd}"
    setup.template:
      name: 'foo'
      pattern: 'foo-*'
      enabled: false
