apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: first
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: second
      port: 9300
      targetPort: 9300