version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.3
    container_name: filebeat
    volumes:
      - /home/mobaxterm/MyDocuments/datapandas/logs_files/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # Add any additional volumes for logs or configurations as needed
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

#docker-compose up -d
